language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ateletin/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true ateletin/react-test npm test
after_success:
  - docker build -t ateletin/multi-docker-client ./client
  - docker build -t ateletin/multi-docker-nginx ./nginx
  - docker build -t ateletin/multi-docker-server ./server
  - docker build -t ateletin/multi-docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ateletin/multi-docker-client
  - docker push ateletin/multi-docker-nginx
  - docker push ateletin/multi-docker-server
  - docker push ateletin/multi-docker-worker
